export const CATEGORIAS_PRODUCTO = [
  'procesador',
  'placa_madre',
  'ram',
  'almacenamiento',
  'gpu',
  'fuente',
  'case',
  'almacenamiento_externo',
  'auricular',
  'parlante',
  'conectividad',
  'estabilizador',
  'ups',
  'monitor',
  'mouse',
  'mousepad',
  'teclado',
  'webcam',
  'cooler_aire',
  'cooler_liquido',
  'antivirus',
  'office',
  'windows',
];

export const LABELS_CATEGORIA = {
  procesador: 'Procesador',
  placa_madre: 'Placa madre',
  ram: 'RAM',
  almacenamiento: 'Almacenamiento',
  gpu: 'GPU',
  fuente: 'Fuente',
  case: 'Case',
  almacenamiento_externo: 'Almacenamiento externo',
  almac_externo: 'Almacenamiento externo',
  auricular: 'Auricular',
  parlante: 'Parlante',
  conectividad: 'Conectividad',
  estabilizador: 'Estabilizador',
  ups: 'UPS',
  monitor: 'Monitor',
  mouse: 'Mouse',
  mousepad: 'Mousepad',
  teclado: 'Teclado',
  webcam: 'Webcam',
  cooler_aire: 'Cooler aire',
  cooler_liquido: 'Cooler liquido',
  antivirus: 'Antivirus',
  office: 'Office',
  windows: 'Windows',
};

export function formatearCategoria(categoria) {
  return LABELS_CATEGORIA[categoria] || String(categoria || '').replace(/_/g, ' ');
}
